---
title: "每週一圖作業資料檔"
output: html_document
params:
  組員: ["林易霆"]  
  學號: ["410473002"]
---

#### 環境設定

以下為老師執行時一定會存在的環境設定
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
rm(list=ls())
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(colorspace); library(grDevices); library(shiny); library(shinyjs); library(scales)
library(tidyr); library(showtext); library(tidyverse); library(colorspace)

#font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(fig.align='center', fig.showtext=T)
```

#### 資料處理
  
```{r data cleaning, echo=TRUE, eval=T}
chu <- read_csv("chuu.csv")

str(chu)

chu <- chu %>% mutate(分類 = as.factor(分類),
                        時間 = lubridate::ymd(時間),
                        line = as.character(
                          ifelse(分類 == "證照/其他表現", NA, 分類))
                        ) %>%
  mutate(分類 = ordered(分類, levels = c("證照/其他表現", "工作", "學業")),
           line = case_when(line == "2" ~ "學業",
                            line == "1" ~ "工作",
                            T ~ line)) %>%
  mutate(line = factor(line, levels = c("工作", "學業"), ordered = T))

# View(chu)

str(chu)

graphData <- list()

graphData$chu <- chu


save(graphData, file = "graphData.rda")
```