---
title: "每週一圖作業4"
output: html_document
params:
  組員: ["林易霆"]  
  學號: ["410473002"]
---

#### 環境設定

以下為老師執行時一定會存在的環境設定
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
rm(list=ls())
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(colorspace); library(grDevices); library(shiny); library(shinyjs); library(scales)
library(tidyr); library(showtext); library(tidyverse); library(colorspace)

#font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(fig.align='center', fig.showtext=T)
```


#### 繪圖程式

```{r graph, echo=T, eval=T}
load(file = "graphData.rda")

# graphData$chu %>% View

graphData$chu %>%
  ggplot() +
  geom_point(aes(x = 時間, y = 分類, color = 分類), shape = 124, size = 6) +
  geom_line(aes(x = 時間, y = line, color = 分類), size = 6) + 
  theme(legend.position = "none",
        axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  scale_y_discrete(labels = c("證照/其他表現" = paste("證照", "其他表現", sep = " \n"), "工作" = "工作經驗", "學業" = "學歷")) +
  annotate("text", x = as.Date("2018-10-01", "%Y-%m-%d"),
           y = 2.25, label = "城市與環境科學學院", size = 3.5) +
  annotate("text", x = as.Date("2016-08-01", "%Y-%m-%d"),
           y = 2.25, label = "社會與區域發展學系", size = 3.5) +
  annotate("text", x = as.Date("2018-11-01", "%Y-%m-%d"),
           y = 1.25, label = paste("台北市都更推動中心",
                                   "專案實習生", sep = "\n"), size = 3.5) +
  annotate("text", x = as.Date("2017-08-01", "%Y-%m-%d"),
           y = 1.25, label = paste("台北市都更處",
                                   "實習生", sep = "\n"), size = 3.5) +
  annotate("text", x = as.Date("2019-07-01", "%Y-%m-%d"),
           y = 3.25, label = paste("Google 雲端",
                                   "應用綜合認證", sep = "\n"), size = 2.75) +
  annotate("text", x = as.Date("2018-10-01", "%Y-%m-%d"),
           y = 3.25, label = "資安認證", size = 2.75) +
  annotate("text", x = as.Date("2018-08-01", "%Y-%m-%d"),
           y = 2.75, label = paste("計算機能力",
                                   "綜合認證", sep = "\n"), size = 2.75) +
  annotate("text", x = as.Date("2018-03-01", "%Y-%m-%d"),
           y = 3.25, label = paste("TQC",
                                   "Excel進階", sep = "\n"), size = 2.75) +
  annotate("text", x = as.Date("2017-11-01", "%Y-%m-%d"),
           y = 2.75, label = paste("資策會",
                                   "菁英培訓計畫", sep = "\n"), size = 2.75) +
  annotate("text", x = as.Date("2017-06-01", "%Y-%m-%d"),
           y = 3.25, label = paste("台北市社區營造",
                                   "人才培訓計畫", sep = "\n"), size = 2.75)

# geom_text or geom_label with position_jitter() doesn't work well
  # had to manually tag all the text labels via annotate()
  
```

#### 設計說明
說明想傳達的訊息（必要）及設計想法（非必要）。寫在***下一行。

*** 

#### 傳遞訊息

將其學歷以及工作經驗以兩條時間軸分開呈現，並在兩條時間軸外標示出曾經參與的特殊活動或是考取的證照。為避免標示上出現重疊、混亂，因此僅標示出較為重要的經歷。
由圖形中可以發現多數的活動都聚集在2017年以後，由此可以推斷履歷所有者在2017年以後十分積極的精進自己的實力，短時間內考取的數個證照也可以作為自主學習能力強的間接證明。