---
title: "課堂練習20191020"
author: "Y.T Lin"
date: "2019/10/23"
output: html_document
---

```{r basic setup, message=FALSE, echo=TRUE, eval=T}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext); library(colorspace); library(scales)
font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```

## 第4周作業

從之前別人畫過的圖來做修正，改用何種geom較適合 或是 有無圖面設計能夠改正的地方。

## 評分標準:

 * 文字描述 (3分)
 * 繪圖方式合適度、geom是否適合 (7分)
 

## 第4章 

### 4.1.3
```{r library data for geom_bar prac}
library(readr)
library100_102 <- read_csv("https://www.dropbox.com/s/wuo5o6l55lk68l6/library100_102.csv?dl=1")

graphList <- list()
```

```{r library data cleaning and drawing}
# some simple data cleaning
library100_102 %>%
  mutate(
    借閱日期=date(ymd_hms(借閱時間)),
    借閱年=year(借閱日期)
  ) -> library100_102 # mutate the time data into date format (lubridate)

library100_102 %>%
  filter(
    借閱日期 %>% 
      dplyr::between(ymd("2014-09-01"),ymd("2015-06-30"))
  ) -> library2014  # between(data, x, y) , to choose the desired time line

library2014 %>%
  group_by(學號) %>%
  summarise(
    學院=last(學院),
    讀者年級=max(讀者年級)
  ) %>%
  ungroup() %>%
  mutate(
    讀者年級=as.factor(讀者年級)
    )-> library2014 
library2014 %>%
  mutate(
    學院=reorder(學院,學號,length,order=T)
    # order the 學院 via the student counts
  ) -> library2014

# Let's get drawing
library2014 %>% 
  ggplot()-> graphList$圖書_ggplotOnly

graphList$圖書_ggplotOnly+
  geom_bar(
    aes(x=學院), fill="#5A99B3", width=0.7
    )
```  
\  

## 4.2 stat function  
\  


```{r stat_count}
graphList$圖書_ggplotOnly+
  geom_bar(
    aes(x=學院)
  )

graphList$圖書_ggplotOnly +
  stat_count(
    aes(x=學院),
    geom="bar" # 使用資料 x=學院 進行count計算，並畫bar
  )

graphList$圖書_ggplotOnly +
  stat_count(
    aes(x=學院, y = stat(count)), 
    geom="bar" # 使用資料 x=學院 進行count計算，並畫bar
  )
# They are in fact, identical


graphList$圖書_ggplotOnly +
  stat_count(
    aes(x=學院, y = stat(prop)), 
    geom="bar" # 使用資料 x=學院 進行prop計算，並畫bar
  )
# prop is the proportion of each group
  # prop calcs the proportion in each 學院, which is of course 100 % = 1

graphList$圖書_ggplotOnly +
  stat_count(
    aes(x=學院, y = stat(prop),
        group = "全校"),  # create a new group "全校", everyone is in the group
    geom="bar" # 使用資料 x=學院 進行prop計算，並畫bar
  )

```  
\  

```{r override geom: stat(count)}
graphList$圖書_ggplotOnly +
  geom_bar(
    aes(x=學院)
  )+
  stat_count(
    aes(x=學院,y=stat(count),label=stat(count)),
    geom="text", vjust = -0.5
  )
```  
\  

```{r override geom: stat(prop)}
graphList$圖書_ggplotOnly +
  geom_bar(
    aes(x=學院,y=stat(prop))
  )+
  stat_count(
    aes(x=學院,y=stat(prop),label=stat(prop)),
    geom="text", vjust = 1.5, colour = "white"
  )
```  
\  

```{r override goem: with groupwise prop}
graphList$圖書_ggplotOnly +
  geom_bar(
    aes(x=學院, y=stat(prop), group="全校") 
  )+
  stat_count(
    aes(x=學院, y=stat(prop), group="全校", label=round(stat(prop),digits=2)),
    geom="text", color="white", vjust = 1.5
  )+
  labs(
    title="各院借閱人次佔總人次比",x="",y=""
  )
```  
\  

## 4.2.3 Overriding Stat

```{r overriding stat}
graphList$圖書_ggplotOnly +
  geom_bar(
    aes(x=學院, y=stat(prop), group="全校") 
  )+
  geom_text(
    aes(x=學院, y=stat(prop), group="全校", label=round(stat(prop),digits=2)),
    stat = "count",
    color = "white",nudge_y = -0.01
  )+
  labs(
    title="各院借閱人次佔總人次比",x="",y=""
  )
```  
\ 

## 4.2.4 Constructing Your Own Stat Function

```{r building your own stat function, eval = F}

stat_function(mapping = NULL, data = NULL, geom = "path",
  position = "identity", ..., fun, xlim = NULL, n = 101,
  args = list(), na.rm = FALSE, show.legend = NA,
  inherit.aes = TRUE)


```

* 會從x軸等距切出許多x值，代到fun設定去計算結果，computed variables: x及y.  
* 說明：https://ggplot2.tidyverse.org/reference/stat_function.html
* fun： 函數名稱  
* n: x軸切多少點  
* args: List of additional arguments to pass to fun  
\  

A little example for further elaboration  
\  

```{r example for stat function construction}

df_y <- data.frame(
  x=rnorm(500,mean=2,sd=1)
)

df_y %>%
  ggplot(aes(x=x))+
  geom_histogram(
    aes(y=stat(density))
  )+
  stat_function(
    fun=dnorm, args = list(mean=2, sd=1) # dnorm 為常態分配density函數
  )
```  
\  

```{r Second Example on stat function construction}
market <- list()

market_demand <- function(x, a=1, b=-1){
  return(a+b*x)
}

market_supply <- function(x, a=0, b=1){
  return(a+b*x)
}

df_grids <- 
  data.frame(
    x=seq(0,1,by=0.2))

df_grids %>%
  ggplot(aes(x=x))+
  stat_function(
    fun="market_demand"
  )+
  stat_function(
    fun="market_supply"
  )+
  scale_y_continuous(
    limits = c(0,1)
  )+
  labs(
    x="Quantity", y="Price"
  ) -> market$demand_supply # draw the big X market graph

market$demand_supply

market$demand_supply+
  stat_function(
    fun="market_demand",
    args=list(b=-2), color='red'
  )
```  
\  

```{r More on the market supply ex.}
market$demand_supply+
  geom_ribbon( # geom_ribbon for the shaded area 
    data=data.frame(x=seq(0.25,0.5,by=0.01)),
    aes(y=x),
    stat="summary", 
    fun.ymin= function(y) market_demand(y),
    fun.ymax= function(y) market_supply(y),
    alpha=0.3
  )
```  
\  

