---
title: "課堂練習 2019 09 25"
author: "Y.T Lin"
date: "2019/9/25"
output: html_document
---
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext)

#font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```

In class code for 2019_09_25.
Today, we will focus on the package "tidyr".

################################# Gather and Spread

```{r make data}
df_gatherExample <- data.frame(
  country=c("A","B","C"),
  `1999`=c("0.7k","37k","212k"),
  `2000`=c("2k","80k","213k"),
  check.names = F
)

## gather() will compress the original df into a smaller df.

df_gatherExample 

gather(df_gatherExample,
       `1999`,`2000`,
       key="年份",value="人口") 
# turn `1999` and `2000` into the variable `年分`, 
  # value of the original df into new variable `人口`
```

```{r gather prac. collegeData}
collegeData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/103_student.csv")

collegeData_gather<- collegeData %>% 
  gather(contains("生"), key = "類別", value = "人數")

```

```{r gather prac2.}
library(readr)
df_taoyuanMarriage <- read_csv("https://data.tycg.gov.tw/opendata/datalist/datasetMeta/download?id=f95d1a33-ec56-44c5-a9ec-3afba8157e39&rid=fd2070ef-7431-4f9c-bc3a-82d7bfbcd2fb")

# 1
df_taoyuanMarriage %>%
  gather(ends_with("月"), key = "月數", value = "對數")
    
  # ALT approach

df_taoyuanMarriage %>%
  gather(-`月份區域別`, key = "月數", value = "對數") 

# 2

df_taoyuanMarriage %>%
  gather(ends_with("月"), key = "月數", value = "對數") %>%
  group_by(月數) %>%
  dplyr::summarise(總結婚對數 = sum(對數))

# 3

df_taoyuanMarriage %>%
  gather(ends_with("月"), key = "月數", value = "對數") %>%
  group_by(月份區域別) %>%
  dplyr::summarise(最高峰月份 = 月數[[which.max(`對數`)]])
```

```{r spread}
df_spreadExample <- data.frame(
  id = c(1,1,1,2,2,2),
  var = c("花朵萼片長度", "學名", "總類數"),
  value = c(5.1, "setosa", 1, 
            7.0, "versicolor", 2))

df_spreadExample

# spread() can expand the df into a bigger df. (?)
   # the opposite of gather()

spread(df_spreadExample,
       var,value)
```

```{r spread prac.}
collegeData_gather %>% spread(類別, 人數) #recover into collegeData


# you need to practice the two Qs by yourself
  # 1
collegeData %>%
  str_detect("")

# TW bank exchange prac.
df_twbankExchangeRate <- read_csv("http://www.bot.com.tw/Govinfo/opendata/csv/151/20180101-20181231-FXCRT.csv")


df_twbankExchangeRate %>%
  select(c(-4)) %>%
  spread(幣別, 即期買入匯率)
```

## Variable Class Changing

```{r tw exchange class change}
df_twbankExchangeRate %>% str()

df_twbankExchangeRate %>%
  mutate(日期 = lubridate::ymd(日期),
         幣別 = as.factor(幣別),
         即期買入匯率 = as.double(即期買入匯率),
         即期賣出匯率 = as.double(即期賣出匯率)) %>%
  str()

```


############################# Data Import

```{r Data Import}
# Watch out the different ENCODING SETTINGS

# Example

library(readr); library(dplyr)
# read in the data by lines

read_lines("http://www.taifex.com.tw/data_gov/taifex_open_data.asp?data_name=DailyForeignExchangeRates") ->
  originalLines

# change the encoding from "CP950" into "UTF-8"
originalLines %>%
  iconv(from="CP950",to="UTF8") %>% 
  read_csv() -> data2

#### IMPORTANT ###
# importing Data will need to specify your locale
  # which can be found in the History chunk after importing the data
read_csv("http://www.taifex.com.tw/data_gov/taifex_open_data.asp?data_name=DailyForeignExchangeRates",
         locale = locale(encoding = "CP950"))

```

```{r change date format}

exchange <- read_csv("http://www.taifex.com.tw/data_gov/taifex_open_data.asp?data_name=DailyForeignExchangeRates",
         locale = locale(encoding = "CP950"))

exchange %>% mutate(日期 = lubridate::ymd(日期)) %>% str()
```

```{r Data import prac.}
factoryinfo<- read_csv("http://www.taiwanplace21.org.tw/Download_File.php?fileName=180312045657_M5.csv")

```

#################### Ch2. GGPLOT Package

```{r ggplot basics}
library(readr)
subsetDataTWbank <- read_csv("https://www.dropbox.com/s/t8ulj3d7cgl8jh5/subsetDataTWbank.csv?dl=1")

subsetDataTWbank %>% str()

# Line plotting 
library(ggplot2)
ggplot(subsetDataTWbank)+
  geom_line(
    aes(x=西元年月,y=`定存利率-一個月-固定`)
  )

  # ALT approach

subsetDataTWbank %>% 
  ggplot(aes(x=西元年月,y=`定存利率-一個月-固定`)) +
  geom_line() + geom_point(color = "red")
```

```{r ggplot 美學對應}
# You need to transform the data to create variable "定存類型" first
  # via gather()
subsetDataTWbank_gather <- subsetDataTWbank %>%
  gather(contains("定存"), key = "定存類型", value = "利率")

subsetDataTWbank_gather %>%
  ggplot()+
  geom_line(
    aes(x=西元年月,y=利率,color=定存類型)
  )

# simple boxplot
subsetDataTWbank_gather %>%
  ggplot(aes(x=定存類型,y=利率)) +
  geom_boxplot()  

# line plot 
subsetDataTWbank_gather %>%
  ggplot()+
  geom_line(
    aes(x=西元年月,y=利率,color=定存類型),
  ) 

subsetDataTWbank %>%
  ggplot(aes(x = 西元年月, y = `定存利率-一個月-固定`)) +
  geom_line(alpha = 0.5, color = "green", size = 1.5)
```

########################### Dealing with String Variables

```{r fun with factors}
# Check the levels' arrangements
subsetDataTWbank_gather$定存類型 %>% 
  as.factor %>% levels

# change the levels positions
subsetDataTWbank_gather %>%
  mutate(
    定存類型=factor(定存類型,levels=c("定存利率-一個月-固定","定存利率-二年期-固定","定存利率-三年期-固定"))
  ) -> subsetDataTWbank_gather

subsetDataTWbank_gather$定存類型 %>% levels()
```


#################### Date Data Formats

```{r lubridate}
twCalendar <- c("民國88年11月1日","民國88年12月1日","民國89年1月1日")

# not AD changing to AD dates

twCalendar %>%
  # 取出字串中的數字部份
  stringr::str_extract_all("[:digit:]+") %>%
  # 將每個日期的「年」數字加上1991再合併年月日成為`yyyy-mm-dd`格式
  purrr::map_chr(
             function(x) {
               x1=as.integer(x[[1]])+1911
               x[[1]]=as.character(x1)
               stringr::str_c(x,collapse="-")
             }
             ) -> westernCalendar

## AD dates change to Date time format

datetimeCalendar <- westernCalendar %>%
  lubridate::ymd()

class(datetimeCalendar)

## Everything in one big code chunk 
subsetDataTWbank %>%
  mutate(
    年月=年月 %>%
      stringr::str_extract_all("[:digit:]+") %>%
      purrr::map_chr(
                 function(x) {
                   x1=as.integer(x[[1]])+1911
                   x[[1]]=as.character(x1)
                                stringr::str_c(x,collapse="-")
                 }
                 ),
    年月日=stringr::str_c(年月,"01",sep="-"), # add in the day (01) for each month
    西元年月日=lubridate::ymd(年月日)
  )

```