---
title: "課堂練習20191009"
author: "Y.T Lin"
date: "2019/10/9"
output: html_document
---

```{r basic setup, message=FALSE, echo=TRUE, eval=T}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext)

#font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```

# 016

```{r}
load(url("https://github.com/tpemartin/course-108-1-inclass-datavisualization/blob/master/%E4%BD%9C%E5%93%81%E5%B1%95%E7%A4%BA/graphData_homework2019-10-08_016.Rda?raw=true"))
graphData %>%
  ggplot()+
  geom_tile(
    aes(x=國家,y=職業,fill=人數)
  )
```

## 3.5 practice

```{r}
load(url("https://github.com/tpemartin/course-108-1-inclass-datavisualization/blob/master/%E4%BD%9C%E5%93%81%E5%B1%95%E7%A4%BA/graphData_homework2019-10-08_014.Rda?raw=true"))

# rename the column names cause its messy and just wrong
colnames(graphData$travelerFromAsia) <- c("年分", "地區", "來台旅遊人數(萬)")

graphData$travelerFromAsia$年分 <- as.numeric(graphData$travelerFromAsia$年分)

graphData$travelerFromAsia %>%
  ggplot(aes(x=`年分`,y=`來台旅遊人數(萬)`,color = 地區, linetype = 地區)) +
  geom_line()
```

```{r teacher's approach}
library(magrittr)

# rename the column names cause its messy and just wrong
colnames(graphData$travelerFromAsia) <- c("年分", "地區", "來台旅遊人數(萬)")

graphData$travelerFromAsia$年分 <- as.numeric(graphData$travelerFromAsia$年分)

graphData$travelerFromAsia$地區 <- as.factor()

graphData$travelerFromAsia %>%
  ggplot(aes(x=`年分`,y=`來台旅遊人數(萬)`,color = 地區, linetype = 地區)) +
  geom_line()
```

# 3.3
```{r CPI practice}
dataCPI <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/PR0101A2Mc.csv", 
    locale = locale(encoding = "BIG5"), skip = 3)

## 改變數名稱
dataCPI %>% 
  dplyr::rename(
    年月=X1,
    CPI=原始值
  ) -> dataCPI

# 移除「有NA」的row
dataCPI %>% na.omit() -> dataCPI

## 調整class
dataCPI$年月 %>% str_c("/01") %>% #擴增為YMD表示
  ymd() -> dataCPI$年月

# 改成2003M1為基期,其指數為100
dataCPI %>% filter(年月==ymd("2003-01-01")) %>% 
  select(CPI) -> CPI2003M1
dataCPI %>% 
  mutate(CPI=CPI/CPI2003M1$CPI*100) -> dataCPI2

# DRAWING 
dataCPI2 %>% ggplot()+
  geom_line(aes(x=年月,y=CPI)) -> basePlot2

basePlot2

# truncate the graph (only show datas after 2003)
dataCPI2 %>% ggplot()+
  geom_line(aes(x=年月,y=CPI)) +
  scale_x_date(limits=c(ymd("2003-01-01"),NA))

# truncate the Y axis as well
dataCPI2 %>% ggplot()+
  geom_line(aes(x=年月,y=CPI)) +
  scale_x_date(limits=c(ymd("2003-01-01"),NA)) +
  scale_y_continuous(limits = c(80, NA))
```

## 3.3.2 Breaks for scale

```{r breaks}
breakDates <- c("2003-01-01",
                "2005-01-01","2010-01-01","2015-01-01",
                "2018-01-01")
breakDates %>% ymd() -> breakDates

basePlot2 +
  scale_x_date(limits=c(ymd("2003-01-01"),NA),
               breaks = breakDates)

# how bout chaning the labels
breakDates <- c("2003-01-01",
                "2005-01-01","2010-01-01","2015-01-01",
                "2018-01-01")
breakDates %>% ymd() -> breakDates

breakLabels <- c("2003",
                 "2005","2010","2015",
                 "2018")
basePlot2 +
  scale_x_date(limits=c(ymd("2003-01-01"),NA),
               breaks = breakDates,
               labels = breakLabels)

# And maybe functions to speed the process
BreakLabel_Fun <- function(x){
  as.character(year(x))
}

basePlot2 +
  scale_x_date(limits=c(ymd("2003-01-01"),NA),
               breaks = breakDates,
               labels = BreakLabel_Fun)
```

```{r break label practice}
# Please change your breakpoints into 民國年

ChinYear <- function(x){
  new.year <- (as.numeric(year(x)) - 1911)
  as.character(new.year)
}

basePlot2 +
  scale_x_date(limits=c(ymd("2003-01-01"),NA),
               breaks = breakDates,
               labels = ChinYear) +
  labs(x = "民國年")
```

# 3.5 practice

```{r practice1 for 3.5}
load(url("https://github.com/tpemartin/course-108-1-inclass-datavisualization/blob/master/%E4%BD%9C%E5%93%81%E5%B1%95%E7%A4%BA/graphData_homework2019-10-07_001.Rda?raw=true"))

c('公投案編號','六都','同意票數','有效票數','同意比例（同意票／有效票）') -> names(graphData$Case_10_result)

colorspace::sequential_hcl(n = 7, h = 321, c = c(85, NA, NA), l = c(25, 95), power = 1.3, rev=FALSE, register = "liberal_palette")

# Attempt to show the liberal scale with sequecial color palette ( wrong though)
graphData$Case_10_result %>% 
  ggplot(aes(y = `同意比例（同意票／有效票）`, x = `六都`)) +
  geom_col(aes(fill=`同意比例（同意票／有效票）`)) +
  geom_text(aes(
      label = str_c(
        round(`同意比例（同意票／有效票）`*100, 1), 
        "%"
      )
    ), 
    size = 3.5, nudge_y = -0.05, color = "grey50") + coord_flip() +
    colorspace::scale_fill_continuous_sequential(
    palette='liberal_palette'
  )+
   scale_y_continuous(
    limits = c(0, 0.8),
    labels = scales::percent_format()
  ) + 
  theme(
    legend.position = "none"
  )


```