---
title: "課堂練習20191016"
author: "Y.T Lin"
date: "2019/10/16"
output: html_document
---
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext); library(colorspace); library(scales)
font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(out.width='80%', fig.asp=.75, fig.align='center', fig.showtext=T)
```


```{r}
load(url("https://github.com/tpemartin/course-108-1-inclass-datavisualization/blob/master/%E4%BD%9C%E5%93%81%E5%B1%95%E7%A4%BA/homework2/graphData_homework2_005.Rda?raw=true"))
## ----graph, echo=T, eval=T-----------------------------------------------
graphData$data %>%
  ggplot(aes(x=年份,y=毛額,color=國民所得_儲蓄_投資毛額))+
  geom_line(aes(linetype=國民所得_儲蓄_投資毛額,size=國民所得_儲蓄_投資毛額))+
  
  scale_linetype_manual(
    values = c("85","12","31"),
    breaks = c(
    "1.4國民所得毛額GNI:1.1+1.2+1.3","3.3國民儲蓄毛額 :2.1+3.2","3.5國內投資毛額"),
    labels = c("所得毛額","儲蓄毛額","投資毛額")
    )+
  theme(legend.position = "none")+
  scale_size_manual(values = c(1,0.5,0.2))+
  
  annotate("text", x = 2016, y = 155000, 
           label = paste("國民所得毛額"), size = 3)+
  annotate("text", x = 2016, y = 70000, 
           label = paste("國民儲蓄毛額"), size = 3) +
  annotate("text", x = 2016, y = 42000, 
           label = paste("國民投資毛額"), size = 3) +
  annotate("text", x = 2010, y = 180000, 
           label = paste("2009年"), size = 3) +
  labs(title = "國民所得、儲蓄、投資毛額",
       caption = "資料來源: 中華民國統計資料網",
       tag = "單位:億(新台幣)")+
  
  geom_vline(aes(xintercept = 2009),linetype="dotted")
```

## geom_rect

```{r}
graphData$events <- data.frame(
      xmin=c(2008, 2013),
      xmax=c(2009, 2014),
      ymin=c(rep(-Inf,2)),
      ymax=c(rep(Inf,2)),
      name=c("2008 \n 次貸危機","2013 \n 歐債危機")
    )

graphData$data %>%
  ggplot()+
  geom_line(aes(x=年份,y=毛額,color=國民所得_儲蓄_投資毛額
                ,linetype=國民所得_儲蓄_投資毛額))+
  geom_rect(
    data=graphData$events,
    mapping=aes(xmin=xmin,xmax=xmax,ymin=ymin,ymax=ymax), alpha=0.1,
    inherit.aes = F) +
  geom_text(
    data=graphData$events,
    aes(x=(xmin+xmax)/2,y=180000,label=name),
    inherit.aes = F
  )
```

```{r, eval = F}
  scale_linetype_manual(
    values = c("85","12","31"),
    breaks = c(
    "1.4國民所得毛額GNI:1.1+1.2+1.3","3.3國民儲蓄毛額 :2.1+3.2","3.5國內投資毛額"),
    labels = c("所得毛額","儲蓄毛額","投資毛額")
    )+
  theme(legend.position = "none")+
  scale_size_manual(values = c(1,0.5,0.2))+
  
  annotate("text", x = 2016, y = 155000, 
           label = paste("國民所得毛額"), size = 3)+
  annotate("text", x = 2016, y = 70000, 
           label = paste("國民儲蓄毛額"), size = 3) +
  annotate("text", x = 2016, y = 42000, 
           label = paste("國民投資毛額"), size = 3) +
  annotate("text", x = 2010, y = 180000, 
           label = paste("2009年"), size = 3) +
  labs(title = "國民所得、儲蓄、投資毛額",
       caption = "資料來源: 中華民國統計資料網",
       tag = "單位:億(新台幣)")
```

## CH 4 Stat Function

 Let's discuss the difference between geom_col and geom_bar.

geom_bar()：用來呈現不同x類別的樣本個數。 樣本個數會自動計算，呈現在y軸。  
\  

geom_col()：用來呈現不同x類別下y值高度。  

```{r geom_col showcase}
startSalaryTopCat<- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/startSalaryTopCat.csv")

# some inchoate data cleaning process
startSalaryTopCat$大職業別[2:7] %>% str_c(.,collapse="','")

startSalaryTopCat %>% filter(
  大職業別 %in% c('工業部門','礦業及土石採取業','製造業','電力及燃氣供應業','用水供應及污染整治業','營造業')
) -> startingSalary_industrial

graphList <- list()

# draw some col graph
startingSalary_industrial %>%
  filter(大職業別 !='工業部門') -> startingSalary_industrial_sub
startingSalary_industrial_sub %>%  
  ggplot(aes(x=大職業別))+
  geom_col(aes(y=`經常性薪資-薪資`))-> graphList$經常薪資_col0

graphList$經常薪資_col0
```  
\  

```{r ALT drawing of the above col graph 1}
startingSalary_industrial_sub %>%
  ggplot()+
  geom_col(
    aes(x=reorder(大職業別,`經常性薪資-薪資`,order = T),y=`經常性薪資-薪資`)
  ) -> graphList$經常薪資_x有排序ed_col1

graphList$經常薪資_x有排序ed_col1
```  
\  

```{r ALT drawing of the above col graph 2}
startingSalary_industrial_sub %>%
  mutate(
    大職業別ordered=reorder(大職業別,
                    `經常性薪資-薪資`,order=T) # order=T才會輸出成ordered factor
  ) -> startingSalary_industrial_sub

startingSalary_industrial_sub %>%
  ggplot()+
  geom_col(
    aes(x=大職業別ordered,y=`經常性薪資-薪資`)
  ) -> graphList$經常薪資_x有排序ed_col0

graphList$經常薪資_x有排序ed_col0
```  
\  

```{r col graph with break orders}
breaks_order <- levels(startingSalary_industrial_sub$大職業別ordered)
# the break_order can be specified by manually giving character strings

startingSalary_industrial_sub %>%
  ggplot()+
  geom_col(
    aes(x=大職業別,y=`經常性薪資-薪資`)
  )+
  scale_x_discrete(
    limits=breaks_order
  ) -> graphList$經常薪資_x有排序ed_scaleLimits_col0

graphList$經常薪資_x有排序ed_scaleLimits_col0
```  
\  

```{r col graph change bar width}
# with width in geom_col(), duh

startingSalary_industrial_sub %>%  
  ggplot(aes(x=大職業別ordered,y=`經常性薪資-薪資`))+
  geom_col(width=0.7)+
  scale_x_discrete(
    limits=breaks_order
  ) -> graphList$經常薪資_x有排序ed_scaleLimits_geomWidth_col0

graphList$經常薪資_x有排序ed_scaleLimits_geomWidth_col0
```  
\  

```{r change ratio of height and width with aspect.ratio}
# aspect.ratio is inserted in cmd theme()
# aspect.ratio = width / height ratio (unaffected by the cmd `coord_flip`)

graphList$經常薪資_x有排序ed_scaleLimits_geomWidth_col0+
  theme(aspect.ratio = 1/1.3) -> 
  graphList$經常薪資_x有排序_scalLimits_gmWidth_asp0_col0

graphList$經常薪資_x有排序_scalLimits_gmWidth_asp0_col0
```  
\  

## 4.1.3 Geom_bar  
\  

```{r library data for geom_bar prac}
library(readr)
library100_102 <- read_csv("https://www.dropbox.com/s/wuo5o6l55lk68l6/library100_102.csv?dl=1")
```

```{r library data cleaning and drawing}
# some simple data cleaning
library100_102 %>%
  mutate(
    借閱日期=date(ymd_hms(借閱時間)),
    借閱年=year(借閱日期)
  ) -> library100_102 # mutate the time data into date format (lubridate)

library100_102 %>%
  filter(
    借閱日期 %>% 
      dplyr::between(ymd("2014-09-01"),ymd("2015-06-30"))
  ) -> library2014  # between(data, x, y) , to choose the desired time line

library2014 %>%
  group_by(學號) %>%
  summarise(
    學院=last(學院),
    讀者年級=max(讀者年級)
  ) %>%
  ungroup() %>%
  mutate(
    讀者年級=as.factor(讀者年級)
    )-> library2014 
library2014 %>%
  mutate(
    學院=reorder(學院,學號,length,order=T)
    # order the 學院 via the student counts
  ) -> library2014

# Let's get drawing
library2014 %>% 
  ggplot()-> graphList$圖書_ggplotOnly

graphList$圖書_ggplotOnly+
  geom_bar(
    aes(x=學院), fill="#5A99B3", width=0.7
    )
```  
\  

```{r library geom_bar add in fill}
graphList$圖書_ggplotOnly +
  geom_bar(
    aes(x=學院,fill=as.factor(讀者年級)), width=0.7
  )
```  
\  

## 4.1.4 Continuous Variable col ( or bar)

```{r continuous variable col}
set.seed(2019)
x <- rnorm(100)

ggplot2::cut_interval(x,n=8) -> x_interval # cut out 8 consecutive intervals
levels(x_interval)

head(x_interval)

df_x <- data.frame(
  x=x,
  x_interval=x_interval
)

df_x %>%
  group_by(x_interval) %>%
  summarise(
    interval_count=n()
  ) %>%
  ungroup() %>% #View
  ggplot(aes(x=x_interval))+
  geom_col(
    aes(y=interval_count)
  )

df_x %>%
  ggplot() +
  geom_density(aes(x = x)) # to show the distribution of x
# No need to cut into 8 intervals. BUT calc by window method, maybe twists the data distribution (UNLESS in big dataset)

# stat(prop) to calc. the proportion

# histogram doesn't change the actual distribution
df_x %>% ggplot() +
  geom_histogram( aes(x = x), bins = 8) # default bins = 30

# How to choose the optimal bins num -> grDevices::nclass.FD(df_x$x)
optimal <- grDevices::nclass.FD(df_x$x) # 10 bins is the best, by SCIENCE

df_x %>% ggplot() +
  geom_histogram( aes(x = x), bins = optimal) # optimal = 10
```  
\  

## 4.2 Stat Function 

```{r stat_count}
graphList$圖書_ggplotOnly+
  geom_bar(
    aes(x=學院)
  )

graphList$圖書_ggplotOnly +
  stat_count(
    aes(x=學院),
    geom="bar" # 使用資料 x=學院 進行count計算，並畫bar
  )

graphList$圖書_ggplotOnly +
  stat_count(
    aes(x=學院, y = stat(count)), 
    geom="bar" # 使用資料 x=學院 進行count計算，並畫bar
  )
# They are in fact, identical


graphList$圖書_ggplotOnly +
  stat_count(
    aes(x=學院, y = stat(prop)), 
    geom="bar" # 使用資料 x=學院 進行prop計算，並畫bar
  )
# prop is the proportion of each group
  # prop calcs the proportion in each 學院, which is of course 100 % = 1

graphList$圖書_ggplotOnly +
  stat_count(
    aes(x=學院, y = stat(prop),
        group = "全校"),  # create a new group "全校", everyone is in the group
    geom="bar" # 使用資料 x=學院 進行prop計算，並畫bar
  )

```

```{r every object size calc.}
sort( sapply(ls(),function(x){object.size(get(x))})) 

jj <- sort( sapply(ls(),function(x){object.size(get(x))})) 
sum(jj)
```