---
title: "每週一圖作業資料檔"
output: html_document
params:
  組員: ["林易霆"]  
  學號: ["410473002"]
---

#### 環境設定

以下為老師執行時一定會存在的環境設定
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
rm(list=ls())
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(colorspace); library(grDevices); library(shiny); library(shinyjs); library(scales)
library(tidyr); library(showtext); library(tidyverse); library(colorspace)

#font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(fig.align='center', fig.showtext=T)
```

#### 資料處理
  
```{r data cleaning, echo=TRUE, eval=T}
transcript <- read_csv("transcript.csv")

# head(transcript)

# str(transcript)

實得學分 <- c(rep(22, 8), rep(25, 9), rep(21, 10),
          rep(23, 9), rep(20, 8), rep(23, 9), rep(21, 8), rep(14, 5))

transcript <- cbind(transcript, 實得學分)

graphData <- list()

graphData$transcript <- transcript %>%
  mutate(學期 = as.factor(學期),
           分類 = as.factor(分類),
           學分 = case_when(學分 == 0 ~ 1,
                            T ~ 學分))

graphData$grouped.transcript <- graphData$transcript %>%
  group_by(學期, 分類) %>%
  summarise(分類學分 = sum(學分),
            學期總平均 = mean(學期總平均),
            學期GPA = mean(學期GPA),
            實得學分 = mean(實得學分)) %>% ungroup()

str(graphData$grouped.transcript)


save(graphData, file = "graphData.rda")
```