---
title: "每週一圖作業資料檔"
output: html_document
params:
  組員: ["林易霆"]  
  學號: ["410473002"]
---

#### 環境設定

以下為老師執行時一定會存在的環境設定
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
rm(list=ls())
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(colorspace); library(grDevices); library(shiny); library(shinyjs); library(scales)
library(tidyr); library(showtext); library(tidyverse); library(colorspace)

#font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(fig.align='center', fig.showtext=T)
```

#### 資料處理
  
```{r data cleaning, echo=TRUE, eval=T}
load(url("https://github.com/tpemartin/course-108-1-inclass-datavisualization/blob/master/%E4%BD%9C%E5%93%81%E5%B1%95%E7%A4%BA/homework3/graphData_homework3_007.Rda?raw=true"))


graphData$population <- graphData$population %>% 
  mutate(年齡層 = as.factor(case_when(
    年齡層 == "65~" ~ "65歲以上",
    年齡層 == "25~64" ~ "25 ~ 64",
    年齡層 == "15~24" ~ "15 ~ 24",
    年齡層 == "0~14" ~ "14歲以下")
      )
    )

str(graphData$population$年齡層)
save(graphData, file = "graphData.rda")
```